package(default_visibility = ["//visibility:public"])

load("//tools:maven.bzl", "t2_java_lib")

t2_java_lib(
    name = "data-api-java",
    srcs = glob(["**/*.java"]),
    artifact_name = "Twiter2 Data API",
    deps = [
    ],
)
