package(default_visibility = ["//visibility:public"])

java_test(
    name = "data-java-test",
    srcs = glob(["*.java"]),
)

filegroup(
    name = "srcs",
    srcs = ["BUILD"] + glob(["**/*.java"]),
)
