package(default_visibility = ["//visibility:public"])

java_library(
   name = "task_scheduler-java",
   srcs = ["edu/iu/dsc/tws/tsched/utils/Task.java",],
   deps = [
       "//twister2/common/src/java:config-java",
       "@commons_cli_commons_cli//jar",
       "@com_google_guava_guava//jar",
   ]
)
