package(default_visibility = ["//visibility:public"])

common_deps_files = [
    "@org_yaml_snakeyaml//jar",
   ]

java_library(
    name = "examples-java",
    srcs = glob(["**/*.java"]),
    deps = common_deps_files,
)
