package(default_visibility = ["//visibility:public"])

filegroup(
    name = "data-srcs",
    srcs = glob(["**"]) + [
        "//twister2/data/src/main/java:srcs",
        "//twister2/data/src/test/java:srcs",
    ],
)