# FROM java:8-jre
FROM openjdk:8-jre-alpine
COPY tmp/twister2-dist/lib/commons-compress-1.15.jar /twister2/lib/
COPY tmp/twister2-dist/lib/protobuf-java-3.4.0.jar /twister2/lib/
COPY tmp/twister2-dist/lib/snakeyaml-1.15.jar /twister2/lib/
COPY tmp/twister2-dist/lib/client-java-1.0.0.jar /twister2/lib/
COPY tmp/twister2-dist/lib/client-java-api-1.0.0.jar /twister2/lib/
COPY tmp/twister2-dist/lib/client-java-proto-1.0.0.jar /twister2/lib/
COPY tmp/twister2-dist/lib/swagger-annotations-1.5.12.jar /twister2/lib/
COPY tmp/twister2-dist/lib/gson-2.6.2.jar /twister2/lib/
COPY tmp/twister2-dist/lib/guava-18.0.jar /twister2/lib/
COPY tmp/twister2-dist/lib/okhttp-2.7.5.jar /twister2/lib/
COPY tmp/twister2-dist/lib/okhttp-ws-2.7.5.jar /twister2/lib/
COPY tmp/twister2-dist/lib/okio-1.6.0.jar /twister2/lib/
COPY tmp/twister2-dist/lib/logging-interceptor-2.7.5.jar /twister2/lib/
COPY tmp/twister2-dist/lib/joda-time-2.9.3.jar /twister2/lib/
COPY tmp/twister2-dist/lib/commons-codec-1.11.jar /twister2/lib/
COPY tmp/twister2-dist/lib/slf4j-api-1.7.7.jar /twister2/lib/
COPY tmp/twister2-dist/lib/slf4j-jdk14-1.7.7.jar /twister2/lib/

