package(default_visibility = ["//visibility:public"])

filegroup(
    name = "conf-yaml",
    srcs = glob(["conf/*.yaml"]),
)

filegroup(
    name = "conf-local-yaml",
    srcs = glob(["conf/local/*.yaml"]),
)

filegroup(
    name = "conf-slurm-yaml",
    srcs = glob(["conf/slurm/*"]),
)

filegroup(
    name = "conf-standalone-yaml",
    srcs = glob(["conf/standalone/*"]),
)

filegroup(
    name = "conf-aurora-yaml",
    srcs = glob(["conf/aurora/*"]),
)

filegroup(
    name = "conf-kubernetes-yaml",
    srcs = glob(["conf/kubernetes/*"]),
)

filegroup(
    name = "conf-kubernetes-deployment-yaml",
    srcs = glob(["conf/kubernetes/deployment/*"]),
)

filegroup(
    name = "conf-mesos-yaml",
    srcs = glob(["conf/mesos/*"]),
)

filegroup(
    name = "conf-nomad-yaml",
    srcs = glob(["conf/nomad/*"]),
)
