package(default_visibility = ["//visibility:public"])

filegroup(
    name = "conf-yaml",
    srcs = glob(["conf/*.yaml"]),
)

filegroup(
    name = "conf-local-yaml",
    srcs = glob(["conf/local/*.yaml"]),
)

filegroup(
    name = "conf-slurmmpi-yaml",
    srcs = glob(["conf/slurmmpi/*"]),
)


filegroup(
    name = "conf-nodesmpi-yaml",
    srcs = glob(["conf/nodesmpi/*"]),
)

filegroup(
    name = "conf-aurora-yaml",
    srcs = glob(["conf/aurora/*"]),
)

filegroup(
    name = "conf-kubernetes-yaml",
    srcs = glob(["conf/kubernetes/*"]),
)

filegroup(
    name = "conf-mesos-yaml",
    srcs = glob(["conf/mesos/*"]),
)

filegroup(
    name = "conf-standalone-yaml",
    srcs = glob(["conf/standalone/*"]),
)
