package(default_visibility = ["//visibility:public"])

filegroup(
    name = "conf-yaml",
    srcs = glob(["conf/*.yaml"]),
)

filegroup(
    name = "conf-local-yaml",
    srcs = glob(["conf/local/*.yaml"]),
)

filegroup(
    name = "conf-slurmmpi-yaml",
    srcs = glob(["conf/slurmmpi/*"]),
)


filegroup(
    name = "conf-nodesmpi-yaml",
    srcs = glob(["conf/nodesmpi/*"]),
)

filegroup(
    name = "conf-aurora-yaml",
    srcs = glob(["conf/aurora/*"]),
)
