package(default_visibility = ["//visibility:public"])

java_library(
    name = "resource_scheduler-java",
    srcs = glob(["**/*.java"]),
    deps = [
        "//twister2/common/src/java:config-java",
        "@commons_cli_commons_cli//jar",
        "//third_party:ompi_javabinding_java",],
)