package(default_visibility = ["//visibility:public"])

common_deps_files = [
    "//twister2/task/src/main/java:task-java"
]

java_library(
    name = "master-java",
    srcs = glob(["**/*.java"]),
    deps = common_deps_files,
)
